version: '3.8'

services:
  php:
    build: .
    container_name: php_container
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - app_network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
